services:
  - name: laba-1
    type: web
    rootDir: backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
  - name: laba-2
    type: web
    rootDir: frontend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
